# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ##############################################
  init1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      result: ${{ steps.step1.outputs.result }}
    steps:
      - id: step1
        run: echo "result=1" >> "$GITHUB_OUTPUT"
  result1:
    name: "Should run #1"
    runs-on: ubuntu-latest
    # Map a step output to a job output
    needs: init1
    steps:
      - id: step1
        run: exit 0
  ##############################################

  ##############################################
  init2:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      result: ${{ steps.step1.outputs.result  == 1 }}
    steps:
      - id: step1
        run: echo "result=0" >> "$GITHUB_OUTPUT"
        
  result2:
    name: "Shouln't run #1"
    runs-on: ubuntu-latest
    # Map a step output to a job output
    needs: init2
    if: ${{needs.init2.outputs.output1 == 1}}
    steps:
      - id: step1
        run: exit -1
  ##############################################

  ##############################################
  exist:
    name: "Secret should exist"
    runs-on: ubuntu-latest
    steps:
      - env:
          secr: ${{secrets.EXIST}}
        shell: bash
        run: |
          if [ -z "$secr" ]; then echo "NULL"; else echo "Not NULL"; fi
  ##############################################
  
  ##############################################
  notExist:
    name: "Secret shouldn't exist"
    runs-on: ubuntu-latest
    steps:
      - env:
          secr: ${{secrets.DO_NOT_EXIST}}
        shell: bash
        run: |
          if [ -z "$secr" ]; then echo "NULL"; else echo "Not NULL"; fi
##############################################


  ##############################################
  exist-v2:
    name: "All secret should exist"
    runs-on: ubuntu-latest
    steps:
      - env:
          secr: ${{secrets.EXIST}}
        shell: bash
        run: |
          check () {
            for var in $*;
             do (if [ -z "${!var}" ]; then return 0; fi);
            done
            return 1;
          }
          check "secr"
          echo "$?"
  ##############################################
